JSON library updates: 1) Added proper Unicon/JSON escape conversions.…
uniconproject/unicon pull request #120
Opened 2020-09-14 04:08 UTC by gkzyoung

… 2) Changed internal procedure names and comments to be more consistent. 3) Added cset support 4) Added jtous() and jtouf() as library functions (will update UTR20 in future)

2020-09-14 04:57 UTC, cjeffery approved these changes

2020-09-14 05:15 UTC, Jafaral commented
@gzkyoung, OpenGL changes should go into a new pull request independent of the json changes.  You can do that by moving the commit to a different branch an opening the pull request from that branch.  I will work with you tomorrow to get this done if you are not familiar with git/github

2020-09-14 05:22 UTC, gkzyoung commented
> @gzkyoung, OpenGL changes should go into a new pull request independent of the json changes. You can do that by moving the commit to a different branch an opening the pull request from that branch. I will work with you tomorrow to get this done if you are not familiar with git/github

2020-09-15 03:09 UTC, Jafaral requested changes
Waiting for a re make to split JSON from openGL changes

2020-09-15 06:51 UTC, closed without merging