Supply the required include definitions to appease clang v12.
uniconproject/unicon pull request #124
Opened 2020-09-17 19:20 UTC by Don-Ward

On macOS the function sysctlbyname() is used in rmemmgt.r.
Clang v11 warned of an implicit definition (because the
needed includes were not present). Clang v12 raises an error.

2020-09-17 19:40 UTC, cjeffery requested changes
This should be addressed in src/h/sys.h where there is currently an #ifdef MacOSX that pulls in sys/sysctl.h. Perhaps someone nuked MacOSX without changing all the references to MacOS, or something like that.

2020-09-17 22:12 UTC, Jafaral requested changes
Just minor comments, Thanks Don!

2020-09-17 22:12 UTC, Jafaral commented on src/runtime/rmemmgt.r
> +
Looks like  you left some dangling white space here!

2020-09-17 22:12 UTC, Jafaral commented on src/h/posix.h
> +#if (defined(BSD) || defined(BSD_4_4_LITE)) && !(defined(MacOSX) || defined(MacOS))
Let us just drop MacOSX @Don-Ward . There is no reason to keep it around.

2020-09-18 13:03 UTC, Jafaral commented
Addressed in #126

2020-09-18 13:03 UTC, closed without merging