basic DFA support
uniconproject/unicon pull request #271
Opened 2022-01-09 04:07 UTC by cjeffery

2022-01-10 16:02 UTC, Jafaral requested changes
Looks good overall. I added comment regarding the use of existing top level Makedefs and Makedef.uni. In this case we may only need to include Makedefs.uni but we need to add CC to it to get the configured C compiler instead of including the two Makedef files and I'm not sure if there are collisions between the two.

2022-01-14 20:54 UTC, cjeffery commented on uni/uflex/Makefile
> +CC=gcc
I agree with this change.  uflex has frequently been built in standalone directories outside of unicon/ but within the Unicon distribution we should make it as clean and portable as we can.

2022-01-14 20:54 UTC, cjeffery commented on uni/uflex/Makefile
> +
Sounds good.

2022-01-14 21:28 UTC, cjeffery commented on uni/uflex/Makefile
> +YACC=win_bison -y
I think these are vestigial references to flex and bison used for building C ulex and not necessary here.

2022-01-18 05:17 UTC, merged