Unidoc: Changed processfile in UniAll to support ulsp
uniconproject/unicon pull request #335
Opened 2023-04-14 16:25 UTC by DuyMach

Add new method in UniAll to grab line directly from raw buff inside UniFile.
Changed UniFile to be able to update (Support for in memory processing)

2023-04-19 01:27 UTC, DuyMach commented
fixed issue from PR, awaiting review

2023-04-19 03:54 UTC, Jafaral requested changes

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniAll.icn
> +           uniFile := UniFile(fName) |
wrong indentation

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniAll.icn
> +            if /uniFile := uniFilez[fName] then {
why do you check for null in `/uniFile`?  do you only want to run this if uniFile is null ?

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniAll.icn
>              uniFile.setSaveSrc(saveSrcFlag)
did you mean to do `uniFile := addFile(fName)` here? `f` isn't used.

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniAll.icn
> +            }
remove whitespace at the end of the line.

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniAll.icn
> +        if /fName | (*fName = 0) then fail
you can shorten this as  if (*\fName) = 0 then fail

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniAll.icn
> +end
add an empty line at the end of the file.

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniFile.icn
> +                       insideFlag, debug, saveSrc, cBuf, isOpen, lineNum)
isOpen is not used.

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniFile.icn
> -    end
why are  you dropping this function.

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniFile.icn
> +        /path:= ""
re-add the space before the colon.

2023-04-19 03:54 UTC, Jafaral commented on uni/unidoc/UniFile.icn
> +end
add a new line at the end of the file.

2023-05-08 14:37 UTC, Jafaral approved these changes

2023-05-08 14:38 UTC, merged